# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17e9737b8f84db66521eda48584cfcbe02b3e583ddb7525fe5ea1841a1423323adb4ef2912abf647489c603b6edd384cec2fcac6fc2ebdaa426b432ece33b0bf

test:
  secret_key_base: b3125edc7bb40f72993fc52a07acc4b2978001d7f90b701714baa048f3df1d67bd30cf38994a5d7e739c60d460db90acbf56bc14e5fbaafdb526d9e1493a7e3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
